### ISSUE TITLE
List of important TODOs before production release

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/sfb1451-projects-catalog#17]
- [ ] there is no summary that communicate how much or the diversity
- [x] navigation is cumbersome: when exploring C06 and then aiming for C07. I need to click the browser back button, which brings me to the top of that long list, not anywhere near where I was
- [ ] keyword search is too limited (only immediate next level)
- [x] First level subdatasets only have code names -- nobody outside this sfb knows what they mean. the keyword shown help, but a title would be better (in addition): https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/15
- [x] showing the gitsha in the subdataset list seems not useful. Labeling it as a version will be confusing to some people (it is more of a state): https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/18
- [x] current metadata still have capitalization errors in people's names -- this comes across as sloppy
- [x] (referring to the dollar sign in funding tab heading) for some reason this icon does not feel right -- i cannot put the finger on it, but it seems needlessly capitalistic. _incoming in catalog PR_
- [x] (`search by dataset or author name`) This field does not seem to search, but to "filter" _incoming in catalog PR_
- [x] (`License: not available`) This has an undesirable double-meaning. The license is "not know", it may well be available for licensing (maybe "unkown" is also better for DOI). _incoming in catalog PR_
- [x] given the "by request" nature of data availability in the SFB, most interested visitors would want to know who a contact person for a dataset would be: https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/19
- [x] Finalize https://github.com/psychoinformatics-de/sfb1451-projects-catalog/pull/14 and merge
- [x] https://github.com/datalad/datalad-catalog/issues/302

TODO: 
1. ~~Create relevant issues for above~~
2. ~~Draw in issues or TODOs from: https://github.com/datalad/datalad-catalog/issues/296~~
3. Do all of the things

**Comment by jsheunis** [comment]
re
>  keyword search is too limited (only immediate next level)

A possible fix for this would be to add all levels of subdatasets also as direct children of the superdataset. A reason for not doing that would be to keep the home page "clean", i.e. only projects showing, although this could also be achieved by custom JS code for this catalog in particular.

An alternative solution would require some code changes in `datalad-catalog` that might have undesirable consequences for performance (recursing through subdatasets, doing an indeterminate amount of get requests along the way, all while waiting for a dataset page to load), and this needs some thinking before/if it turns into tangible code.

**Comment by jsheunis** [comment]
re 
>  navigation is cumbersome: when exploring C06 and then aiming for C07. I need to click the browser back button, which brings me to the top of that long list, not anywhere near where I was

There won't be time to fix this before going to production, but this is useful feedback to take back into datalad-catalog development. IMO.

**Comment by jsheunis** [comment]
re 

> there is no summary that communicate how much or the diversity

Would this be on the catalog level, e.g. summary information about all included datasets, that will be displayed on the catalog home page? We'd need to get a few specs together before deciding how best to implement this, and how it influences general catalog UX.

**Comment by adswa** [comment]
adding an observation from chat I couldn't yet find:

- The Binder link from e.g., https://psychoinformatics-de.github.io/sfb1451-projects-catalog/#/dataset/a808f9e1-d638-4771-ae4c-ff21da29151a/272e2844cd7c58dda8dfe288e7831ad2fa9c34b6 is called "/gh/datalad/datalad-binder/parameter-test", which isn't an optimal name. @jsheunis comment in the chat was:

> should rename that repo/notebook, i think it was initially used as a test and when it worked the test in the name just remained. the notebook receives a URL paramer in the form of the datalad dataset url, which is then fed into a code cell in the notebook, so that users can run all cells without having to copy and paste the dataset url.

**Comment by jsheunis** [comment]
> adding an observation from chat I couldn't yet find:
> - The Binder link from e.g., https://psychoinformatics-de.github.io/sfb1451-projects-catalog/#/dataset/a808f9e1-d638-4771-ae4c-ff21da29151a/272e2844cd7c58dda8dfe288e7831ad2fa9c34b6 is called "/gh/datalad/datalad-binder/parameter-test", which isn't an optimal name. @jsheunis comment in the chat was...

Also mentioned here: https://github.com/datalad/datalad-catalog/issues/296. I have fixed a bunch of those bugs in latest catalog main, and left the ones that I thought are not needed for SFB catalog. But I think perhaps this one is also useful to fix, since people might click on the binder link. Everything related to this can be done in catalog proper, and then ported into SFB catalog.

**Comment by adswa** [comment]
ah sorry for the noise then :see_no_evil:

**Comment by jsheunis** [comment]
No noise, you brought it back to the top again which was necessary

**Comment by jsheunis** [comment]
Added the relevant issue to the top list: https://github.com/datalad/datalad-catalog/issues/302

**Comment by mslw** [comment]
I checked two more boxes, because they have been addressed since (navigation by adding back button, and later also removing project datasets; datasets having code names by removing the project datasets; request contact by adding a dedicated button).

Of the remaining, I no longer know what the first meant ("there is no summary that communicate how much or the diversity"), and the other two ("keyword search is too limited" and "update everything binder") seem to be broader datalad-catalog items, and also not very impactful compared to those already addressed.

I would consider this issue mostly addresed. Given that we are now past the "production release" (publication under https://data.sfb1451.de), the issue has served its purpose, and can be closed.
